version: '3.3'
services:
  db:
    image: postgres:10.6-alpine
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: demo4Db
      POSTGRES_USER: demo4user
      POSTGRES_PASSWORD: demo4password


#version: '3.3'
#services:
#  db:
#    image: postgres:10.6-alpine
#    restart: always
##    ports:
##       - '5433:5432'
#    environment:
#      - POSTGRES_DB=demo4_local
#      - POSTGRES_USER_NAME=user1
#      - POSTGRES_PASSWORD=password1