spring:
  type: com.zaxxer.hikari.HikariDataSource
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5433/demo4_local
  username: user
  password: password
  hikari:
    minimumIdle: 1
    maximumPoolSize: 10
    validationQuery: SELECT 1
  jooq:
    sql-dialect: postgres
  flyway:
    enabled: false